services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
       - POSTGRES_DB=rams_db
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_HOST=db
       - POSTGRES_PORT=5432
    depends_on:
       db:
         condition: service_healthy
    restart: on-failure
  db:
     image: postgres
     restart: always
     user: postgres
     volumes:
       - ./data:/docker-entrypoint-initdb.d
     environment:
       - POSTGRES_DB=rams_db
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_HOST=localhost
       - POSTGRES_PORT=5432
     ports:
       - 5432:5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5 
volumes:
  db-data:
